### ISSUE TITLE
error installing tensorflow  in SpatialDDLS-env environment

### ISSUE THREAD

**Issue by daymecita** [diegommcc/SpatialDDLS#3]
Hello!

Thank you very much for the package. I am very curious to test it with my data. However, I am getting an error when using the function installTFpython. It successfully creates the SpatialDDLS-env environment but when it starts installing all dependencies needed for tensorflow I get an error related to typing-extensions (which is one of the dependencies). Apparently it found it in another python location and wants to uninstall it. I don't have write permissions on that location but I would expect that the installation is done in the  
SpatialDDLS-env environment. Any clue about how to solve it? 

Dayme

installTFpython(install.conda = TRUE)

=== Creating SpatialDDLS-env environment
+ /usr/prog/Conda/23.1.0/bin/conda 'create' '--yes' '--name' 'SpatialDDLS-env' 'python==3.8' '--quiet' '-c' 'conda-forge'
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/gonzad1f/.conda/envs/SpatialDDLS-env

  added / updated specs:
    - python==3.8

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge 
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu 
  ca-certificates    conda-forge/linux-64::ca-certificates-2024.7.4-hbcca054_0 
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.40-hf3520f5_7 
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007 
  libgcc             conda-forge/linux-64::libgcc-14.1.0-h77fa898_1 
  libgcc-ng          conda-forge/linux-64::libgcc-ng-14.1.0-h69a702a_1 
  libgomp            conda-forge/linux-64::libgomp-14.1.0-h77fa898_1 
  libsqlite          conda-forge/linux-64::libsqlite-3.46.0-hde9e2c9_0 
  libstdcxx          conda-forge/linux-64::libstdcxx-14.1.0-hc0a3c3a_1 
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-14.1.0-h4852527_1 
  libzlib            conda-forge/linux-64::libzlib-1.2.13-h4ab18f5_6 
  ncurses            conda-forge/linux-64::ncurses-6.5-he02047a_1 
  openssl            conda-forge/linux-64::openssl-1.1.1w-hd590300_0 
  pip                conda-forge/noarch::pip-24.2-pyhd8ed1ab_0 
  python             conda-forge/linux-64::python-3.8.0-h357f687_5 
  readline           conda-forge/linux-64::readline-8.2-h8228510_1 
  setuptools         conda-forge/noarch::setuptools-72.2.0-pyhd8ed1ab_0 
  sqlite             conda-forge/linux-64::sqlite-3.46.0-h6d4b2fc_0 
  tk                 conda-forge/linux-64::tk-8.6.13-noxft_h4845f30_101 
  wheel              conda-forge/noarch::wheel-0.44.0-pyhd8ed1ab_0 
  xz                 conda-forge/linux-64::xz-5.2.6-h166bdaf_0 
  zlib               conda-forge/linux-64::zlib-1.2.13-h4ab18f5_6 

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

=== Installing tensorflow in SpatialDDLS-env environment
+ . /usr/prog/Conda/23.1.0/bin/activate
+ conda activate 'SpatialDDLS-env'
+ '/home/gonzad1f/.conda/envs/SpatialDDLS-env/bin/python' -m pip install --upgrade --no-user 'numpy<2' 'tensorflow-cpu==2.6.*'
Requirement already satisfied: numpy<2 in /usr/prog/SciPy-bundle/2023.02-gfbf-2023a/lib/python3.11/site-packages (1.25.1)
Collecting tensorflow-cpu==2.6.*
  Using cached tensorflow_cpu-2.6.5-cp38-cp38-manylinux2010_x86_64.whl.metadata (2.9 kB)
Collecting numpy<2
  Using cached numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl.metadata (2.0 kB)
Collecting absl-py~=0.10 (from tensorflow-cpu==2.6.*)
  Using cached absl_py-0.15.0-py3-none-any.whl.metadata (2.4 kB)
Collecting astunparse~=1.6.3 (from tensorflow-cpu==2.6.*)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting clang~=5.0 (from tensorflow-cpu==2.6.*)
  Using cached clang-5.0-py3-none-any.whl
Collecting flatbuffers~=1.12.0 (from tensorflow-cpu==2.6.*)
  Using cached flatbuffers-1.12-py2.py3-none-any.whl.metadata (872 bytes)
Collecting google-pasta~=0.2 (from tensorflow-cpu==2.6.*)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting h5py~=3.1.0 (from tensorflow-cpu==2.6.*)
  Using cached h5py-3.1.0-cp38-cp38-manylinux1_x86_64.whl.metadata (2.1 kB)
Collecting keras-preprocessing~=1.1.2 (from tensorflow-cpu==2.6.*)
  Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl.metadata (1.9 kB)
Collecting opt-einsum~=3.3.0 (from tensorflow-cpu==2.6.*)
  Using cached opt_einsum-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting protobuf<3.20,>=3.9.2 (from tensorflow-cpu==2.6.*)
  Using cached protobuf-3.19.6-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (787 bytes)
Collecting six~=1.15.0 (from tensorflow-cpu==2.6.*)
  Using cached six-1.15.0-py2.py3-none-any.whl.metadata (1.8 kB)
Collecting termcolor~=1.1.0 (from tensorflow-cpu==2.6.*)
  Using cached termcolor-1.1.0-py3-none-any.whl
Collecting typing-extensions<3.11,>=3.7 (from tensorflow-cpu==2.6.*)
  Using cached typing_extensions-3.10.0.2-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: wheel~=0.35 in /home/gonzad1f/.conda/envs/SpatialDDLS-env/lib/python3.8/site-packages (from tensorflow-cpu==2.6.*) (0.44.0)
Collecting wrapt~=1.12.1 (from tensorflow-cpu==2.6.*)
  Using cached wrapt-1.12.1-cp38-cp38-linux_x86_64.whl
Collecting gast==0.4.0 (from tensorflow-cpu==2.6.*)
  Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
Collecting tensorboard<2.7,>=2.6.0 (from tensorflow-cpu==2.6.*)
  Using cached tensorboard-2.6.0-py3-none-any.whl.metadata (1.9 kB)
Collecting tensorflow-estimator<2.7,>=2.6.0 (from tensorflow-cpu==2.6.*)
  Using cached tensorflow_estimator-2.6.0-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting keras<2.7,>=2.6.0 (from tensorflow-cpu==2.6.*)
  Using cached keras-2.6.0-py2.py3-none-any.whl.metadata (1.3 kB)
Collecting grpcio<2.0,>=1.37.0 (from tensorflow-cpu==2.6.*)
  Using cached grpcio-1.66.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.9 kB)
Collecting google-auth<2,>=1.6.3 (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached google_auth-1.35.0-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting google-auth-oauthlib<0.5,>=0.4.1 (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting markdown>=2.6.8 (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached Markdown-3.7-py3-none-any.whl.metadata (7.0 kB)
Collecting requests<3,>=2.21.0 (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: setuptools>=41.0.0 in /home/gonzad1f/.conda/envs/SpatialDDLS-env/lib/python3.8/site-packages (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*) (72.2.0)
Collecting tensorboard-data-server<0.7.0,>=0.6.0 (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl.metadata (1.1 kB)
Collecting tensorboard-plugin-wit>=1.6.0 (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached tensorboard_plugin_wit-1.8.1-py3-none-any.whl.metadata (873 bytes)
Collecting werkzeug>=0.11.15 (from tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached werkzeug-3.0.4-py3-none-any.whl.metadata (3.7 kB)
Collecting cachetools<5.0,>=2.0.0 (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached cachetools-4.2.4-py3-none-any.whl.metadata (4.8 kB)
Collecting pyasn1-modules>=0.2.1 (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached pyasn1_modules-0.4.0-py3-none-any.whl.metadata (3.4 kB)
Collecting rsa<5,>=3.1.4 (from google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached rsa-4.9-py3-none-any.whl.metadata (4.2 kB)
Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached requests_oauthlib-2.0.0-py2.py3-none-any.whl.metadata (11 kB)
Collecting importlib-metadata>=4.4 (from markdown>=2.6.8->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached importlib_metadata-8.4.0-py3-none-any.whl.metadata (4.7 kB)
Collecting charset-normalizer<4,>=2 (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached charset_normalizer-3.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached idna-3.8-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached urllib3-2.2.2-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests<3,>=2.21.0->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
Collecting MarkupSafe>=2.1.1 (from werkzeug>=0.11.15->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached MarkupSafe-2.1.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Collecting zipp>=0.5 (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached zipp-3.20.1-py3-none-any.whl.metadata (3.7 kB)
Collecting pyasn1<0.7.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth<2,>=1.6.3->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached pyasn1-0.6.0-py2.py3-none-any.whl.metadata (8.3 kB)
Collecting oauthlib>=3.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.7,>=2.6.0->tensorflow-cpu==2.6.*)
  Using cached oauthlib-3.2.2-py3-none-any.whl.metadata (7.5 kB)
Using cached tensorflow_cpu-2.6.5-cp38-cp38-manylinux2010_x86_64.whl (178.3 MB)
Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
Using cached numpy-1.19.5-cp38-cp38-manylinux2010_x86_64.whl (14.9 MB)
Using cached absl_py-0.15.0-py3-none-any.whl (132 kB)
Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Using cached flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Using cached grpcio-1.66.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.8 MB)
Using cached h5py-3.1.0-cp38-cp38-manylinux1_x86_64.whl (4.4 MB)
Using cached keras-2.6.0-py2.py3-none-any.whl (1.3 MB)
Using cached Keras_Preprocessing-1.1.2-py2.py3-none-any.whl (42 kB)
Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Using cached protobuf-3.19.6-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Using cached tensorboard-2.6.0-py3-none-any.whl (5.6 MB)
Using cached tensorflow_estimator-2.6.0-py2.py3-none-any.whl (462 kB)
Using cached typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Using cached google_auth-1.35.0-py2.py3-none-any.whl (152 kB)
Using cached google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Using cached Markdown-3.7-py3-none-any.whl (106 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
Using cached tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
Using cached werkzeug-3.0.4-py3-none-any.whl (227 kB)
Using cached cachetools-4.2.4-py3-none-any.whl (10 kB)
Using cached certifi-2024.7.4-py3-none-any.whl (162 kB)
Using cached charset_normalizer-3.3.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (141 kB)
Using cached idna-3.8-py3-none-any.whl (66 kB)
Using cached importlib_metadata-8.4.0-py3-none-any.whl (26 kB)
Using cached MarkupSafe-2.1.5-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26 kB)
Using cached pyasn1_modules-0.4.0-py3-none-any.whl (181 kB)
Using cached requests_oauthlib-2.0.0-py2.py3-none-any.whl (24 kB)
Using cached rsa-4.9-py3-none-any.whl (34 kB)
Using cached urllib3-2.2.2-py3-none-any.whl (121 kB)
Using cached oauthlib-3.2.2-py3-none-any.whl (151 kB)
Using cached pyasn1-0.6.0-py2.py3-none-any.whl (85 kB)
Using cached zipp-3.20.1-py3-none-any.whl (9.0 kB)
Installing collected packages: wrapt, typing-extensions, termcolor, tensorflow-estimator, tensorboard-plugin-wit, keras, flatbuffers, clang, zipp, urllib3, tensorboard-data-server, six, pyasn1, protobuf, oauthlib, numpy, MarkupSafe, idna, grpcio, gast, charset-normalizer, certifi, cachetools, werkzeug, rsa, requests, pyasn1-modules, opt-einsum, keras-preprocessing, importlib-metadata, h5py, google-pasta, astunparse, absl-py, requests-oauthlib, markdown, google-auth, google-auth-oauthlib, tensorboard, tensorflow-cpu
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.7.1
    Uninstalling typing_extensions-4.7.1:
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/usr/prog/SciPy-bundle/2023.02-gfbf-2023a/lib/python3.11/site-packages/__pycache__/typing_extensions.cpython-311.pyc'
Consider using the `--user` option or check the permissions.

Error: Error during the installation. Please see the website of the package and/or the vignettes for more details

**Comment by diegommcc** [comment]
Hi @daymecita! First, so sorry for the delay. 

It seems that tensorflow=2.6 requires typing-extensions<3.11,>=3.7, but conda finds an existing newer version. With full permissions, it does not seem to raise an error, but considering that you don't have write permissions, I see that tensorflow=2.7 allows newer versions of typing-extensions, so I would try to change it. You can do it using the R package as follows: 

```r
installTFpython(tensorflow.version = "2.7")
```

Before running the function, I would remove the failed `SpatialDDLS-env` created in the first attempt. 

Let me know if it works. Good luck!
